### ISSUE TITLE
Wrong number of triangles in most the alps area

### ISSUE THREAD

**Issue by jppa320** [oscarpilote/Ortho4XP#271] opened 2024-06-27 08:48 UTC

**Comment by jppa320** [comment] 2024-06-27 08:51
This is the message I just sento to Wiewfinderpanorama
Hello Jonathan.
First of all, thank you for your excellent work and thank you for making it available for all of us.

I use your data for the sceneries of my X-Plane simulator through a tool called Ortho4Xp which uses your data to build its mesh.
I have used this for many years now and was very satisfied of the result.
However, I recently started a new round of building sceneries which I already had built in the past and noticed that in the area of central Europe, in the Alps, the number of triangles I was getting for mess were much smaller as usual.
To make the long story short, I made a number o f tests which lead to the conclusion that you data have changed a lot and do not seem as satisfactory as before. It happens that I saved a few files from your site some 2 years ago. If I take tile N46E008 as an example, the data available todau lead me to a mesh with 310.823 triangles. The data coming form your site and saved by me 2years ago give me 5.755.170 triangles for the same tile. The last number is more what we expect to get.
Do you have an idea of what the probmem can be.
Additional info is that the problem is concentrated to an area around north of French Alps, Switzerland, Austria and northern Italy. Others area in Europe seems to be still ok.

Thanl you for your help

JP.Pelissier

**Comment by d41k4n** [comment] 2024-06-27 11:32
Duplicate of https://github.com/oscarpilote/Ortho4XP/issues/226 (same root cause)

**Closed by d41k4n** 2024-06-27 11:32 UTC

**Comment by jppa320** [comment] 2024-06-27 13:30
Merci Oscar pour cette réponse. Jonathan me jure que ses liens sont bon.

 

Je ne suis pas un expert de python, mais avec plus de 60 ans d’expérience informatique derrière moi (hé oui j’ai passé 80) je tente de lire le code source O4_DEM_Utility.py et je vois la séquence :

 

            if deferranti_letter + deferranti_nbr in (

                "O31",

                "P31",

                "N32",

                "O32",

                "P32",

                "Q32",

                "N33",

                "O33",

                "P33",

                "Q33",

                "R33",

                "O34",

                "P34",

                "Q34",

                "R34",

                "O35",

                "P35",

                "Q35",

                "R35",

                "P36",

                "Q36",

                "R36",

            ):

                resol = 1

            else:

                resol = 3

 

Ne serait-ce pas la source du problème ?

 

Bien à vous

 

JPP

 

 

De : d41k4n ***@***.*** 
Envoyé : jeudi 27 juin 2024 13:33
À : oscarpilote/Ortho4XP
Cc : jppa320; Author
Objet : Re: [oscarpilote/Ortho4XP] Wrong number of triangles in most the alps area (Issue #271)

 

Closed #271 <https://github.com/oscarpilote/Ortho4XP/issues/271>  as completed.

**Comment by w8sl** [comment] 2024-06-27 17:01
No, the problem is there:
 if source == "View":
        # Viewfinderpanorama grouping of files and resolutions is a 
        # bit complicated...
        if (lat, lon) in (
            (44, 5),
            (45, 5),
            (46, 5),
            (43, 6),
            (44, 6),
            (45, 6),
            (46, 6),
            (47, 6),
            (43, 7),
            (44, 7),
            (45, 7),
            (46, 7),
            (47, 7),
            (45, 8),
            (46, 8),
            (47, 8),
            (45, 9),
            (46, 9),
            (47, 9),
            (45, 10),
            (46, 10),
            (47, 10),
            (45, 11),
            (46, 11),
            (47, 11),
            (45, 12),
            (46, 12),
            (47, 12),
            (46, 13),
            (47, 13),
            (46, 14),
            (47, 14),
            (46, 15),
            (47, 15),
        ):
            resol = 1
            url = (
                "http://viewfinderpanoramas.org/dem1/"
                + os.path.basename(FNAMES.base_file_name(lat, lon)).lower()
                + ".zip"
            )

I have solved this by re-using withdrawn PR194, but I am not the author of the main code. I have only added option to manually select 1" or 3" elev. data, as there is some missing data in 1" elev. for Europe
[O4_DEM_Utils.py.zip](https://github.com/user-attachments/files/16018527/O4_DEM_Utils.py.zip)

[O4_File_Names.py.zip](https://github.com/user-attachments/files/16018525/O4_File_Names.py.zip)

**Comment by jppa320** [comment] 2024-06-27 18:38
Pardon my bad knowledge, but I do not know if python source is interpreted or compiled.in other terms can I modify the python source of O4_DEM_utilits.py  by just updating the tile list to better fit the reality.

 

Regards

 

JPP 

 

De : w8sl ***@***.*** 
Envoyé : jeudi 27 juin 2024 19:02
À : oscarpilote/Ortho4XP
Cc : jppa320; Author
Objet : Re: [oscarpilote/Ortho4XP] Wrong number of triangles in most the alps area (Issue #271)

 

No, the problem is there:
if source == "View":
# Viewfinderpanorama grouping of files and resolutions is a
# bit complicated...
if (lat, lon) in (
(44, 5),
(45, 5),
(46, 5),
(43, 6),
(44, 6),
(45, 6),
(46, 6),
(47, 6),
(43, 7),
(44, 7),
(45, 7),
(46, 7),
(47, 7),
(45, 8),
(46, 8),
(47, 8),
(45, 9),
(46, 9),
(47, 9),
(45, 10),
(46, 10),
(47, 10),
(45, 11),
(46, 11),
(47, 11),
(45, 12),
(46, 12),
(47, 12),
(46, 13),
(47, 13),
(46, 14),
(47, 14),
(46, 15),
(47, 15),
):
resol = 1
url = (
"http://viewfinderpanoramas.org/dem1/"
+ os.path.basename(FNAMES.base_file_name(lat, lon)).lower()
+ ".zip"
)

I have solved this by re-using withdrawn PR194, but I am not the author of the main code. I have only added option to manually select 1" or 3" elev. data, as there is some missing data in 1" elev. for Europe
O4_DEM_Utils.py.zip <https://github.com/user-attachments/files/16018527/O4_DEM_Utils.py.zip> 

O4_File_Names.py.zip <https://github.com/user-attachments/files/16018525/O4_File_Names.py.zip>

**Comment by w8sl** [comment] 2024-06-28 04:17
Only source code of Python script version can be modified by user. Recommended solution is indeed to unzip much better, complete 1" dataset from https://sonny.4lima.de into Elevation_data directory, place https://github.com/Jordan886/demfilesorganizer script in the same directory and run it from there. It requires only basic download and Python instalation from python.org.
Or just copy old Elevation_data from 1.30
