### ISSUE TITLE
Mesh building fails +48-003 asking for bug report

### ISSUE THREAD

**Issue by Cad01** [oscarpilote/Ortho4XP#125] opened 2020-04-29 08:42 UTC
Step 2 : Building mesh for tile +48-003 : 
--------

-> Modifying curv_tol weight map according to runway locations.
-> Modifying curv_tol weight map according to coastline location.
    * Recycling OSM data from .\OSM_data\+40-010\+48-003\+48-003_coastline.osm.bz2
-> Start of the mesh algorithm Triangle4XP.
   Loading altitudes from DEM file.

   Loading curv_tol geographic weights.

   Computing curvatures from altitudes.

   Constructing Delaunay triangulation by divide-and-conquer method.

   Recovering segments in Delaunay triangulation.

   Internal error in segmentintersection():

   Topological inconsistency after splitting a segment.

   Splitting subsegment (0.7803597, 0.5709207) (0.780358137985, 0.571076022852) at (0.780358137985, 0.571076022852).

WARNING: Triangle4XP could not achieve the requested quality (min_angle), most probably due to an uncatched OSM error.
It will be tempted now with no angle constraint (i.e. min_angle=0).
   Loading altitudes from DEM file.

   Loading curv_tol geographic weights.

   Computing curvatures from altitudes.

   Constructing Delaunay triangulation by divide-and-conquer method.

   Recovering segments in Delaunay triangulation.

   Internal error in segmentintersection():

   Topological inconsistency after splitting a segment.

   Splitting subsegment (0.7803597, 0.5709207) (0.780358137985, 0.571076022852) at (0.780358137985, 0.571076022852).

ERROR: Triangle4XP really couldn't make it !

If the reason is not due to the limited amount of RAM please
file a bug including the .node and .poly files that you
will find in E:/Ortho4XP-master\zOrtho4XP_+48-003.
## 16gb RAM availible

[Data+48-003.node.zip.zip](https://github.com/oscarpilote/Ortho4XP/files/4550572/Data%2B48-003.node.zip.zip)
[Data+48-003.poly.zip.zip](https://github.com/oscarpilote/Ortho4XP/files/4550574/Data%2B48-003.poly.zip.zip)

**Comment by d41k4n** [comment] 2020-04-29 15:44
Duplicate of #122

**Closed by d41k4n** 2020-04-29 15:44 UTC
