### ISSUE TITLE
Viewfinderpanoramas Error for area around +57+021

### ISSUE THREAD

**Issue by mmaechtel** [oscarpilote/Ortho4XP#228] opened 2024-03-13 20:46 UTC
Hi,

For 57+021 I get Viewfinder Error in 1.3 and 1.4. I'm not sure if this it due to 'no data' there or it is a problem receiving/Parsing the hgt binary data in Ortho4XP? Do I have to change something for this area (I'm new in this area with ortho4xp :) ).

See the outptut of 1.4 as an example. 1.3 flattens also.

Tnx
Mike

`Batch build launched for a number of 1 tiles.
Dealing with tile  1 / 1 : +57+021

Step 1 : Building vector data for tile +57+021 : 

-> Dealing with airports
    * Recycling OSM data from .\OSM_data\+50+020\+57+021\+57+021_airports.osm.bz2
   EVVA   Ventspils International Airport                              1 runway , lat= 57.36, lon= 21.54
   Loading elevation data and smoothing it over airports.
    Downloading  .\Elevation_data\+50+020\N57E021.hgt from Viewfinderpanoramas (J. de Ferranti).
[WinError 2] The system cannot find the file specified: '.\\Elevation_data\\+50+020\\N57E021.hgt'
    ERROR: in reading elevation from .\Elevation_data\+50+020\N57E021.hgt -> replaced with zero altitude.
    Downloading  .\Elevation_data\+50+020\N57E022.hgt from Viewfinderpanoramas (J. de Ferranti).
[WinError 2] The system cannot find the file specified: '.\\Elevation_data\\+50+020\\N57E022.hgt'
    ERROR: in reading elevation from .\Elevation_data\+50+020\N57E022.hgt -> replaced with zero altitude.
    Downloading  .\Elevation_data\+50+020\N56E021.hgt from Viewfinderpanoramas (J. de Ferranti).
[WinError 2] The system cannot find the file specified: '.\\Elevation_data\\+50+020\\N56E021.hgt'
    ERROR: in reading elevation from .\Elevation_data\+50+020\N56E021.hgt -> replaced with zero altitude.
    Downloading  .\Elevation_data\+50+020\N56E020.hgt from Viewfinderpanoramas (J. de Ferranti).
[WinError 2] The system cannot find the file specified: '.\\Elevation_data\\+50+020\\N56E020.hgt'
    ERROR: in reading elevation from .\Elevation_data\+50+020\N56E020.hgt -> replaced with zero altitude.
    Downloading  .\Elevation_data\+50+020\N56E022.hgt from Viewfinderpanoramas (J. de Ferranti).
[WinError 2] The system cannot find the file specified: '.\\Elevation_data\\+50+020\\N56E022.hgt'
    ERROR: in reading elevation from .\Elevation_data\+50+020\N56E022.hgt -> replaced with zero altitude.
    Downloading  .\Elevation_data\+50+020\N58E021.hgt from Viewfinderpanoramas (J. de Ferranti).
[WinError 2] The system cannot find the file specified: '.\\Elevation_data\\+50+020\\N58E021.hgt'
    ERROR: in reading elevation from .\Elevation_data\+50+020\N58E021.hgt -> replaced with zero altitude.
    Downloading  .\Elevation_data\+50+020\N58E022.hgt from Viewfinderpanoramas (J. de Ferranti).
[WinError 2] The system cannot find the file specified: '.\\Elevation_data\\+50+020\\N58E022.hgt'
    ERROR: in reading elevation from .\Elevation_data\+50+020\N58E022.hgt -> replaced with zero altitude.
    * Min altitude: 0.0 , Max altitude: 0.0 , Mean: 0.0
   Auto-patched 1 runway and 3 pieces of taxiway.
   Flattened 1 helipads.
   Number of edges at this point: 377`

**Comment by mmaechtel** [comment] 2024-03-15 16:01
Maybe I need custom_dem for Lettland and Estland ?

**Comment by d41k4n** [comment] 2024-03-15 17:43
This is either due to breaking changes or a temporary issue on viewfinderpanoramas.org. It looks like the downloaded zip at https://viewfinderpanoramas.org/dem1/O34.zip is missing some tiles compared to sometime in the past.

You can either [contact](https://viewfinderpanoramas.org/) the responsible (J. de Ferranti) and complain or manually download the 3" DEM for the region via https://viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org3.htm and extract/copy the .hgt files into the correct subfolder(s) under Elevation_data.

**Comment by d41k4n** [comment] 2024-03-15 18:08
See also https://github.com/oscarpilote/Ortho4XP/issues/226#issuecomment-2000183418.

**Comment by w8sl** [comment] 2024-03-17 05:34
It is relatively easy to have worldwide and robust 3" elevation data from Viewfinderpanoramas downloaded automatically. 
1" data is also working as per PR194, but it is not bug free. I prefer switch for manual selection of 1" or 3". Works well on 1.30 (also 1.40 - not uploaded yet)

**Comment by mmaechtel** [comment] 2024-04-14 09:26
many thanks, I changed to Sonny's Lidars for Europe 3 weeks ago and have no more problems with ortho4xp 1.4. Works great. Many thanks!

**Comment by sierrawhiskyhotel** [comment] 2024-05-01 14:05
Is there somehow a better description on how to make this work now? I cannot motivate o4xp to do anything not-flat. I have downloaded the files above, i have added them to the folders, but it doesn't change anything for me..., i don't even get an error message that hgt files are missing, anyhow all flat... Any suggestions?

**Comment by w8sl** [comment] 2024-05-02 19:46
Download all files (30 GB unzipped) from Sonny and use this:

https://forums.x-plane.org/index.php?/forums/topic/304657-python-script-to-automatically-place-dem-files-in-the-elevation_data-folder-structure/

**Comment by d41k4n** [comment] 2024-06-27 11:31
Duplicate of https://github.com/oscarpilote/Ortho4XP/issues/226 (same root cause)

**Closed by d41k4n** 2024-06-27 11:31 UTC
